import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

// Uploaded images are saved on disk in ./uploads, OUTSIDE the public folder, so they can only be
// reached through /api/attachments/[id] (which checks who is asking). Each file is named by its
// attachment id. To move to cloud storage later (S3, etc.), replace only the functions in this file.
const UPLOAD_DIR = path.join(process.cwd(), "uploads");

function filePath(id: string): string {
  // Ids are generated by us, but never let an odd id walk out of the uploads folder.
  if (!/^[A-Za-z0-9-]+$/.test(id)) throw new Error("Invalid file id");
  return path.join(UPLOAD_DIR, id);
}

export async function saveFile(id: string, data: Buffer): Promise<void> {
  await mkdir(UPLOAD_DIR, { recursive: true });
  await writeFile(filePath(id), data);
}

export function readStoredFile(id: string): Promise<Buffer> {
  return readFile(filePath(id));
}

export async function deleteStoredFiles(ids: string[]): Promise<void> {
  await Promise.all(ids.map((id) => rm(filePath(id), { force: true })));
}
