import { DeleteObjectsCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

// Where uploaded photos are kept. Every photo is named by its attachment id, and is only ever shown
// through /api/attachments/[id] or a share link, which check who is asking.
//
//  - Online: an S3-compatible bucket (Cloudflare R2, AWS S3, Supabase Storage...). Turned on by setting S3_BUCKET.
//  - On your computer: the ./uploads folder, when S3_BUCKET is not set.
//
// The rest of the app only uses saveFile, readStoredFile and deleteStoredFiles below.

const bucket = process.env.S3_BUCKET;
const uploadDir = path.join(process.cwd(), "uploads");

function fileName(id: string): string {
  // Ids are generated by us, but never let an odd id walk out of the folder or bucket prefix.
  if (!/^[A-Za-z0-9-]+$/.test(id)) throw new Error("Invalid file id");
  return id;
}

let client: S3Client | undefined;
function s3(): S3Client {
  const accessKeyId = process.env.S3_ACCESS_KEY_ID;
  const secretAccessKey = process.env.S3_SECRET_ACCESS_KEY;
  if (!accessKeyId || !secretAccessKey) throw new Error("Photo storage is not set up: S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY are missing (see DEPLOY.md).");

  client ??= new S3Client({
    region: process.env.S3_REGION || "auto", // "auto" is what Cloudflare R2 expects
    endpoint: process.env.S3_ENDPOINT || undefined, // leave empty for AWS S3
    forcePathStyle: process.env.S3_FORCE_PATH_STYLE === "true",
    credentials: { accessKeyId, secretAccessKey },
  });
  return client;
}

const key = (id: string) => `photos/${fileName(id)}`;

export async function saveFile(id: string, data: Buffer): Promise<void> {
  if (bucket) {
    await s3().send(new PutObjectCommand({ Bucket: bucket, Key: key(id), Body: data }));
    return;
  }
  if (process.env.NODE_ENV === "production") {
    // Online hosts don't keep files written to disk, so photos would silently disappear.
    throw new Error("Photo storage is not set up: set S3_BUCKET and the other S3_ settings (see DEPLOY.md).");
  }
  await mkdir(uploadDir, { recursive: true });
  await writeFile(path.join(uploadDir, fileName(id)), data);
}

export async function readStoredFile(id: string): Promise<Buffer> {
  if (bucket) {
    const result = await s3().send(new GetObjectCommand({ Bucket: bucket, Key: key(id) }));
    if (!result.Body) throw new Error("File not found");
    return Buffer.from(await result.Body.transformToByteArray());
  }
  return readFile(path.join(uploadDir, fileName(id)));
}

export async function deleteStoredFiles(ids: string[]): Promise<void> {
  if (ids.length === 0) return;

  if (bucket) {
    // S3 deletes up to 1,000 files per request.
    for (let start = 0; start < ids.length; start += 1000) {
      const batch = ids.slice(start, start + 1000);
      await s3().send(new DeleteObjectsCommand({ Bucket: bucket, Delete: { Objects: batch.map((id) => ({ Key: key(id) })), Quiet: true } }));
    }
    return;
  }
  await Promise.all(ids.map((id) => rm(path.join(uploadDir, fileName(id)), { force: true })));
}
